language: node_js
node_js:
  - 8
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run deploy-storybook -- --ci
deploy:
  provider: heroku
  app: bootcamp-gdg-frontend
  api_key:
    secure: 'u3m2anOTPYElq5xiYhAnaTvwM0WOMe9TeHebszuQ8wvKjSqLqw2mNCgimSfQF72gZodNK8dI3hHdZEISWAiqTM3VzADsjSQGaxW/QkMPepF4makAvQCGwaaWPQqcfq7spASJLhfKAnUpvjykjdKoRhjvoVOkSdob/PulMWdIrE0zC9buGeMRqmIynJ60K2TQjiGee6YOl30T9sVQX2dD4Kr8P7oc7mnDsaqvFmwYE58EhimKj961KXbjwyQPNkwoDZAGQxKMBaiSlzPh99hyo214VFFlLan+y8PK2BR90BTVX4ROVW8Tirm+oletYT14lbp/QKfEnOLtDmpuCwWvIQ0kukRAJdzquDNB/xNnnhVUerdfkrEpEMsyIs4dyiUpCH0oaKYJc7bxpOUJOC0UKQvOfFXNOBxmsttCUMWTP3VwzH+mX5Pz4Qoq+kGyiJKfTsqUipOEnasL3lt9U6/X/AD6aTy0vpIbQtFU90khKjB8SaxjoxK+upkwN0SezWi1m3iCwvb1yqgwCoP6p0QiSF+mqahMEfBrDce/ho9cq5SjP9F+RGlNpYgr/3KfhEEN/dunblL2+YEl0UjjDAnGZ/iVRPHBnUIE3rqBT9sdKMqLxgLFNpoWub8o1GQIVUmiP3o2l3XL36ox2euRzBbTsfnxnonHhzegXnB51/L7pks='
